apiVersion: v1
kind: Service
metadata:
  name: janusserver
  labels:
    run: janusserver
spec:
  ports:
  - name: port8188
    protocol: TCP
    port: 8188
    targetPort: 8188
  - name: port8088
    protocol: TCP
    port: 8088
    targetPort: 8088
  - name: port8089
    protocol: TCP
    port: 8089
    targetPort: 8089
  - name: port8889
    protocol: TCP
    port: 8889
    targetPort: 8889
  - name: port8000
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: port7088
    protocol: TCP
    port: 7088
    targetPort: 7088
  - name: port7089
    protocol: TCP
    port: 7089
    targetPort: 7089
  - name: port10000
    protocol: UDP
    port: 10000
    targetPort: 10000
  selector:
    app: janusserver
  type: NodePort