apiVersion: v1
kind: Pod
metadata:
  name: godaddypodcreatertest
spec:
  containers:
    - image: coffeebreak
      name: coffeebreak
      imagePullPolicy: Never
      resources: {}
      ports:
        - containerPort: 8080